# Generated by Django 5.1.1 on 2024-10-03 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingschedulerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendars',
            name='meetings',
        ),
        migrations.AddField(
            model_name='meetings',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetingschedulerapp.calendars'),
        ),
    ]
