# Generated by Django 5.1.1 on 2024-10-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingschedulerapp', '0002_remove_calendars_meetings_meetings_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='meetingschedulerapp.calendars'),
        ),
    ]
