# Generated by Django 5.1.1 on 2024-10-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingschedulerapp', '0003_rename_meeting_id_attachments_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetingschedulerapp.meetings'),
        ),
    ]
