# Generated by Django 5.1.1 on 2024-10-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingschedulerapp', '0004_alter_participants_meeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetingschedulerapp.meetings'),
        ),
    ]
