# Generated by Django 5.1.1 on 2024-10-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetingschedulerapp', '0005_alter_attachments_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachments',
            old_name='meeting',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='calendar',
            new_name='calendar_id',
        ),
        migrations.RenameField(
            model_name='participants',
            old_name='meeting',
            new_name='meeting_id',
        ),
    ]
